# Generated by Django 3.2.10 on 2022-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersapp", "0002_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлен"),
        ),
    ]
