# Generated by Django 3.2.10 on 2022-02-03 15:57

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_user_model_extend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 5, 15, 57, 45, 363608, tzinfo=utc),
                verbose_name="время актуальности ключа",
            ),
        ),
    ]
